version: "3.7"

services:
  nginx:
    image: my/docker-nginx-static-site:latest
    volumes:
      - "./files:/files"
      - "./nginx.conf:/etc/nginx/nginx.conf"
      # - "./conf:/etc/nginx/conf.d"

    ports:
      - "8080:80"
